name: 💡 Feature Add & Enhancements
description: Feature Add & Enhancements
title: "Task: "
labels: ["enhancement"]
assignees: "rkkoranteng"
projects: "RKKoranteng/23"
body:
     
  - type: textarea
    id: User-Story
    attributes:
      label: User Story
      placeholder: |
        As a ,
        I want to ,
        So that ,
    validations:
      required: true
      
  - type: checkboxes
    id: Acceptance-Criteria
    attributes:
      label: Acceptance Criteria
      options:
        - label: Code Quality - All tasks for the story are completed and reviewed
          check: true
        - label: Security and Compliance - Code has been reviewed for sensitive stuff like passwords etc 
          check: true
        - label: Testing - Feature add/enhancements work as expected
          check: true
        - label: Documentation - User guide completed. I need this for my future reference 😅
          check: true
        - label: No Tech-Debt - The deployment checklist is completed and the acceptance criteria in the story are met.
          check: true
    validations:
      required: true
