name: 💡 Feature Add & Enhancements
description: Feature Add & Enhancements
title: "Task: "
labels: ["enhancement"]
assignees: "rkkoranteng"
projects: "RKKoranteng/23"
body:
     
  - type: textarea
    id: User-Story
    attributes:
      label: User Story
      placeholder: |
        As a ,
        I want to ,
        So that ,
    validations:
      required: true
      
  - type: textarea
    id: Acceptance-Criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        **Definition of Done**
        - [x] All tasks for the story are completed and reviewed.
        - [x] Code has been reviewed for secrets before merging into the main branch.
        - [x] Unit tests cover at least 85% of the code and pass successfully.
        - [x] Acceptance criteria in the story are met.
        - [x] Documentation completed for the new/enhanced feature.
        - [x] The deployment checklist is completed, and the feature is ready for release.
        
    validations:
      required: true
 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell
