name: 💡 Feature Add & Enhancements
description: Feature Add & Enhancements
title: "Task: "
labels: ["enhancement"]
assignees: "rkkoranteng"
projects: "RKKoranteng/23"
body:
     
  - type: textarea
    id: User-Story
    attributes:
      label: User Story
      placeholder: |
        As a ,
        I want to ,
        So that ,
    validations:
      required: true
      
  - type: textarea
    id: Acceptance-Criteria
    attributes:
      label: Acceptance Criteria
      value: |
        **Definition of Done**
        - ☑ **Code Quality**: All tasks for the story are completed and reviewed.
        - ☑ **Security and Compliance**: Code has been reviewed for sensitive stuff like passwords etc 
        - ☑ **Testing**: Feature add/enhancements work as expected 
        - ☑ **Documentation**: User guide completed. I need this for my own future reference
        - ☑ **No Tech-Debt**: The deployment checklist is completed and the acceptance criteria in the story are met.
        
    validations:
      required: true
 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell
