name: 💡 Task
description: File a bug/issue
title: "Task: <title>"
labels: ["enhancement"]
body:
     
  - type: textarea
    id: User-Story
    attributes:
      label: User Story
      placeholder: |
        As a ,
        I want to ,
        So that ,
    validations:
      required: true
      
  - type: textarea
    id: Acceptance-Criteria
    attributes:
      label: Acceptance Criteria
      description: Definition of Done
      placeholder: |
        ### Implementation Notes
        ---
        
        ### Testing Notes
        ---

        ### Dependencies
        ---
       
        ### Resources
        ---
        
    validations:
      required: true
 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell
